feeds:
  - "https://www.reuters.com/markets/feeds/summary.rss"
  - "https://www.reuters.com/technology/rss"
  - "https://www.investing.com/rss/news_25.rss"
  - "https://www.finviz.com/feed.ashx"  # 접근 가능시
language: "en"
video:
  target_seconds: 58
  size:
    width: 1080
    height: 1920
  font_path: "/System/Library/Fonts/Supplemental/Arial Unicode.ttf"
  subtitle_font_size: 56
  margin: 64
audio:
  loudness_target_lufs: -14
broll:
  min_height: 1920
  orientation: "portrait"
  search_terms: ["stocks","markets","wall street","chart","trading","economy","macro"]
upload:
  privacy_status: "public"  # public | unlisted | private
  default_tags: ["stocks","markets","finance","economy","inflation","fed","etf","earnings"]
  disclaimer: "This video is for informational purposes only and is not financial advice."
runtime:
  max_items_per_run: 2
  retries: 3
  request_timeout_sec: 25
